### ISSUE TITLE
Feature: Logging in

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/kwetter-kweet-service#1]
**Description**
As a User, I want to be able to log in the application, so I can start tweeting.

**Acceptance Criteria**
- Should be able to log in to the application with a Google account

**Test cases**
- [x] TC01Login to the application with a Google account

**Tasks**
- [x] Add Roles to Auth0
- [x] Assign Auth0-Roles with JWT Roles
- [x] Create Login form
