### ISSUE TITLE
Feature: Search user

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/kwetter-kweet-service#13]
**Description**
As a User, I want to search for other users, so I can easily type the name of the user I want to find

**Acceptance Criteria**
- Should be able to find user by typing username.

**Test cases**
- [ ] TC01 Type name of user I want to find.

**Tasks**
- [ ] Prepare according data
- [ ] Create Logic to search users.
